# Generated by Django 4.1.5 on 2023-01-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('tid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('salary', models.PositiveIntegerField()),
                ('work_exp', models.PositiveIntegerField()),
                ('Date_of_join', models.DateField()),
                ('photo', models.ImageField(upload_to='timages')),
            ],
        ),
    ]
