# Generated by Django 4.1.5 on 2023-01-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='subject',
            field=models.ManyToManyField(to='Batch.subject'),
        ),
    ]
